/*
 * Copyright 2024 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(add_double.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(9f1719420691efa4723f74fb25edeef2)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <flaress/add_double.h>
// pydoc.h is automatically generated in the build directory
#include <add_double_pydoc.h>

void bind_add_double(py::module& m)
{

    using add_double    = ::gr::flaress::add_double;


    py::class_<add_double, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<add_double>>(m, "add_double", D(add_double))

        .def(py::init(&add_double::make),
           py::arg("vlen") = 1,
           D(add_double,make)
        )
        



        ;




}








