/*
 * Copyright 2024 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(add_const_double.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(d9741e71231e7d2fc0d49948f13e607b)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/flaress/add_const_double.h>
// pydoc.h is automatically generated in the build directory
#include <add_const_double_pydoc.h>

void bind_add_const_double(py::module& m)
{

    using add_const_double    = ::gr::flaress::add_const_double;


    py::class_<add_const_double, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<add_const_double>>(m, "add_const_double", D(add_const_double))

        .def(py::init(&add_const_double::make),
           py::arg("k"),
           py::arg("vlen"),
           D(add_const_double,make)
        )
        




        
        .def("set_k",&add_const_double::set_k,       
            py::arg("k"),
            D(add_const_double,set_k)
        )

        ;




}








