/*
 * Copyright 2024 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(add.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(e230fbe071631a7eaf732ed72c3b4e07)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/flaress/add.h>
// pydoc.h is automatically generated in the build directory
#include <add_pydoc.h>

template <typename T>
void bind_add_template(py::module& m, const char* classname)
{
    using add = gr::flaress::add<T>;

    py::class_<add,
               gr::sync_block,
               gr::block,
               gr::basic_block,
               std::shared_ptr<add>>(m, classname)
        .def(py::init(&gr::flaress::add<T>::make), py::arg("vlen") = 1);
}

void bind_add(py::module& m)
{
    bind_add_template<double>(m, "add_double");
    bind_add_template<int64_t>(m, "add_int64");
}
