/*
 * Copyright 2024 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(divide_double.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(f540cd3373d7fcae8832a6fcf6c6c2f7)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <flaress/divide_double.h>
// pydoc.h is automatically generated in the build directory
#include <divide_double_pydoc.h>

void bind_divide_double(py::module& m)
{

    using divide_double    = ::gr::flaress::divide_double;


    py::class_<divide_double, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<divide_double>>(m, "divide_double", D(divide_double))

        .def(py::init(&divide_double::make),
           py::arg("vlen"),
           D(divide_double,make)
        )
        



        ;




}








