/*
 * Copyright 2024 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(divide_int64.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(4b5912b3309af1f9f07166df4392f448)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <flaress/divide_int64.h>
// pydoc.h is automatically generated in the build directory
#include <divide_int64_pydoc.h>

void bind_divide_int64(py::module& m)
{

    using divide_int64    = ::gr::flaress::divide_int64;


    py::class_<divide_int64, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<divide_int64>>(m, "divide_int64", D(divide_int64))

        .def(py::init(&divide_int64::make),
           py::arg("vlen"),
           D(divide_int64,make)
        )
        



        ;




}








