/*
 * Copyright 2024 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(fixed_point_math_dd.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(8d665b060ae2db85658335f3b7a2abcc)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/flaress/fixed_point_math_dd.h>
// pydoc.h is automatically generated in the build directory
#include <fixed_point_math_dd_pydoc.h>

void bind_fixed_point_math_dd(py::module& m)
{

    using fixed_point_math_dd    = ::gr::flaress::fixed_point_math_dd;


    py::class_<fixed_point_math_dd, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<fixed_point_math_dd>>(m, "fixed_point_math_dd", D(fixed_point_math_dd))

        .def(py::init(&fixed_point_math_dd::make),
           py::arg("vlen"),
           py::arg("N_int"),
           py::arg("N_frac"),
           D(fixed_point_math_dd,make)
        )
        



        ;




}








