/*
 * Copyright 2024 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(fixed_point_math_cc.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(2343412155cda636504c9ab2f47b35dc)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <flaress/fixed_point_math_cc.h>
// pydoc.h is automatically generated in the build directory
#include <fixed_point_math_cc_pydoc.h>

void bind_fixed_point_math_cc(py::module& m)
{

    using fixed_point_math_cc    = ::gr::flaress::fixed_point_math_cc;


    py::class_<fixed_point_math_cc, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<fixed_point_math_cc>>(m, "fixed_point_math_cc", D(fixed_point_math_cc))

        .def(py::init(&fixed_point_math_cc::make),
           py::arg("vlen"),
           py::arg("N_int"),
           py::arg("N_frac"),
           D(fixed_point_math_cc,make)
        )
        



        ;




}








