/*
 * Copyright 2024 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(fixed_point_math_ff.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(1c3bbd51a28756139cf5004e57f77b21)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/flaress/fixed_point_math_ff.h>
// pydoc.h is automatically generated in the build directory
#include <fixed_point_math_ff_pydoc.h>

void bind_fixed_point_math_ff(py::module& m)
{

    using fixed_point_math_ff    = ::gr::flaress::fixed_point_math_ff;


    py::class_<fixed_point_math_ff, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<fixed_point_math_ff>>(m, "fixed_point_math_ff", D(fixed_point_math_ff))

        .def(py::init(&fixed_point_math_ff::make),
           py::arg("vlen"),
           py::arg("N_int"),
           py::arg("N_frac"),
           D(fixed_point_math_ff,make)
        )
        



        ;




}








