/*
 * Copyright 2024 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(int_to_int64.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(936956a56e024bea1b4136273d9e71c3)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <flaress/int_to_int64.h>
// pydoc.h is automatically generated in the build directory
#include <int_to_int64_pydoc.h>

void bind_int_to_int64(py::module& m)
{

    using int_to_int64    = ::gr::flaress::int_to_int64;


    py::class_<int_to_int64, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<int_to_int64>>(m, "int_to_int64", D(int_to_int64))

        .def(py::init(&int_to_int64::make),
           py::arg("vlen") = 1,
           py::arg("scale") = 1,
           D(int_to_int64,make)
        )
        




        
        .def("scale",&int_to_int64::scale,       
            D(int_to_int64,scale)
        )


        
        .def("set_scale",&int_to_int64::set_scale,       
            py::arg("scale"),
            D(int_to_int64,set_scale)
        )

        ;




}








