/*
 * Copyright 2024 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(multiply_double.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(005b3ed8acfd38c7f927342d1cd60379)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/flaress/multiply_double.h>
// pydoc.h is automatically generated in the build directory
#include <multiply_double_pydoc.h>

void bind_multiply_double(py::module& m)
{

    using multiply_double    = ::gr::flaress::multiply_double;


    py::class_<multiply_double, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<multiply_double>>(m, "multiply_double", D(multiply_double))

        .def(py::init(&multiply_double::make),
           py::arg("vlen"),
           D(multiply_double,make)
        )
        



        ;




}








