/*
 * Copyright 2024 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(snr.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(726bb75bfab7c4c0fbccb086bb96af1f)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/flaress/snr.h>
// pydoc.h is automatically generated in the build directory
#include <snr_pydoc.h>

void bind_snr(py::module& m)
{

    using snr    = ::gr::flaress::snr;


    py::class_<snr, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<snr>>(m, "snr", D(snr))

        .def(py::init(&snr::make),
           py::arg("auto_carrier"),
           py::arg("carrier"),
           py::arg("all_spectrum"),
           py::arg("freq_central"),
           py::arg("samp_rate"),
           py::arg("nintems"),
           py::arg("signal_bw"),
           py::arg("noise_bw"),
           D(snr,make)
        )
        



        ;




}








