/*
 * Copyright 2024 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(vector_sink_double.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(48b526663af6ffad65fd2670843948d4)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <flaress/vector_sink_double.h>
// pydoc.h is automatically generated in the build directory
#include <vector_sink_double_pydoc.h>

void bind_vector_sink_double(py::module& m)
{

    using vector_sink_double    = ::gr::flaress::vector_sink_double;


    py::class_<vector_sink_double, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<vector_sink_double>>(m, "vector_sink_double", D(vector_sink_double))

        .def(py::init(&vector_sink_double::make),
           py::arg("vlen") = 1,
           py::arg("reserve_items") = 1024,
           D(vector_sink_double,make)
        )
        




        
        .def("reset",&vector_sink_double::reset,       
            D(vector_sink_double,reset)
        )


        
        .def("data",&vector_sink_double::data,       
            D(vector_sink_double,data)
        )


        
        .def("tags",&vector_sink_double::tags,       
            D(vector_sink_double,tags)
        )

        ;




}








