/*
 * Copyright 2024 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(vector_sink_int64.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(3f15610081c3dd314889f627ac38e63c)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <flaress/vector_sink_int64.h>
// pydoc.h is automatically generated in the build directory
#include <vector_sink_int64_pydoc.h>

void bind_vector_sink_int64(py::module& m)
{

    using vector_sink_int64    = ::gr::flaress::vector_sink_int64;


    py::class_<vector_sink_int64, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<vector_sink_int64>>(m, "vector_sink_int64", D(vector_sink_int64))

        .def(py::init(&vector_sink_int64::make),
           py::arg("vlen") = 1,
           py::arg("reserve_items") = 1024,
           D(vector_sink_int64,make)
        )
        




        
        .def("reset",&vector_sink_int64::reset,       
            D(vector_sink_int64,reset)
        )


        
        .def("data",&vector_sink_int64::data,       
            D(vector_sink_int64,data)
        )


        
        .def("tags",&vector_sink_int64::tags,       
            D(vector_sink_int64,tags)
        )

        ;




}








